### ISSUE TITLE
Lag and Audio Being Dropped with Wowza

### ISSUE THREAD

**Issue by jd-alexander** [ks3sdk/KSYLiveAndroidSDK#10]
There's a constant lag and audio is being dropped when streaming with this library to WOWZA server. I can guarantee my internet works well so i know it's some issue with library. I ran the example and I was having the issues.

**Comment by tian9246** [comment]
I don't hava WOWZA server so i can't test this. Could you mail me a URL to test? And have you test an other kind of phone or version of Android?

**Comment by jd-alexander** [comment]
Yes will email URL. Dont want it to be public

**Comment by tian9246** [comment]
ok Thank you very muchi will have a try tomorrow..

**Comment by jd-alexander** [comment]
Okay let me know how it goes. Thanks for your help. Appreciate it
