### ISSUE TITLE
KsyRecordClient类中直接修改了SurfaceView的layoutparam，导致控制SurfaceView高宽不方便

### ISSUE THREAD

**Issue by lsjwzh** [ks3sdk/KSYLiveAndroidSDK#6]
KsyRecordClient类中直接修改了SurfaceView的layoutparam，导致控制SurfaceView高宽不方便

**Comment by lsjwzh** [comment]
setUpCamera只判断了SurfaceView 的高宽，导致传入TextureView时，程序崩溃

**Comment by tian9246** [comment]
https://github.com/ks3sdk/KSYLiveAndroidSDK/commit/1946f76203d57922f64b441225b02fc298fde6f0 fix that
